[supervisord]
nodaemon=true

[program:celery-node]
command=python celery_worker.py server
; Redirect stdout to supervisord's stdout
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
; Redirect stderr to supervisord's stderr
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
; Ensure the process runs in the foreground and does not daemonize itself
nodaemon=true

[program:stellar-daemon]
command=/usr/bin/stellar node --no-socket
redirect_stderr=true
stdout_logfile=/var/log/supervisor/stellar_daemon.log
nodaemon=true
